# Generated by Django 4.2.3 on 2023-08-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('mob', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('add', models.CharField(max_length=100)),
            ],
        ),
    ]
